# dbt_project.yml
name: neuefische_da_180825_analytics_engineering_project
version: '1.0'
config-version: 2

# The dbt profile to use (must exist in your dbt Cloud environment or local profiles.yml)
profile: 's_jingwang'

# Paths for dbt resources
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directory for compiled SQL
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  neuefische_da_180825_analytics_engineering_project:
    staging:
      +schema: s_jingwang
    prep:
      +schema: s_jingwang
    mart:
      +schema: s_jingwang