# dbt_project.yml
name: neuefische_da_180825_analytics_engineering_project
version: '1.0.0'
config-version: 2

# The dbt profile to use (must exist in your dbt Cloud environment or local profiles.yml)
profile: 'default'

# Paths for dbt resources
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directory for compiled SQL
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Models configuration
models:
  neuefische_da_180825_analytics_engineering_project:
    # All models under models/staging/ will go to the 'staging' schema
    staging:
      materialized: table

# Optional placeholders for other folders (if you have them)
    prep:
      materialized: table
    mart:
      materialized: table


